#!/usr/bin/env bash

# Display numbers from 1 to 20, handling superstitious numbers

for i in {1..20}; do
  case $i in
    4)
      echo "$i bad luck from China"
      ;;
    9)
      echo "$i bad luck from Japan"
      ;;
    17)
      echo "$i bad luck from Italy"
      ;;
    *)  # Default case for all other numbers
      echo "$i"
      ;;
  esac
done

